### ISSUE TITLE
gallery in RC

### ISSUE THREAD

**Issue by KinoSeed** [mewlips/nx-remote-controller-mod#10]
just updated nx-ks with v0.9, but since it's stripped down version I'm not sure if the gallery is ready or not.
I take it, it needs to be generated first? 

For now I simply added in installation " ln -sf /sdcard/DCIM /opt/usr/nx-ks/nx-rc/web_root/DCIM " to allow browsing of the image directories.  

To save resources maybe adding a button "generate gallery" to the controller can be used to run "generate_gallery.sh", which will create a gallery-folder and we can have the iframe point there? Or you have different idea? 

Could you also add the arm binaries for  dcraw, cjpeg, djpeg, exif  ( couldn't compile them here), it they will be needed for the gallery generation. 

btw, I added "ported for nx-ks" in the "about", since it's somewhat cut down, and if something is not working on behalf of my doing, it would be clear the source may not be the issue.  (so if you have that in your main distro, it's really not needed to be there)

**Comment by mewlips** [comment]
> just updated nx-ks with v0.9, but since it's stripped down version I'm not sure if the gallery is ready or not.
> I take it, it needs to be generated first?

Gallery is not ready now. current gallery is just browsing the DCIM folder, that is provided by mongoose library.
The real gallery will be Implemented in the next version. 

> For now I simply added in installation " ln -sf /sdcard/DCIM /opt/usr/nx-ks/nx-rc/web_root/DCIM " to allow browsing of the image directories.

Actually, there is no need to create symlink in installation. RC daemon will create the symlink if not exist. 

> To save resources maybe adding a button "generate gallery" to the controller can be used to run "generate_gallery.sh", which will create a gallery-folder and we can have the iframe point there? Or you have different idea?

i composed the generate_gallery.sh script for testing purpose. My idea is
- monItoring DCIM folder using the inotify
- when user taked photo, RC will extract embedded thumbnail from the newly created jpg file
- gallery page will update lively.

> Could you also add the arm binaries for dcraw, cjpeg, djpeg, exif ( couldn't compile them here), it they will be needed for the gallery generation.

when gallery is done , arm binaries also will provide.

> btw, I added "ported for nx-ks" in the "about", since it's somewhat cut down, and if something is not working on behalf of my doing, it would be clear the source may not be the issue. (so if you have that in your main distro, it's really not needed to be there)

Okay. i will remove it from main distro. you can add it when  port rc to nx-ks. :-)

**Comment by KinoSeed** [comment]
using inotify - sounds even better :)
(working only when gallery is selected/visible I hope)

btw, in my case the sym-link was not created, or if created, was not at the proper place.
(so I added it in the installation procedure)

**Comment by mewlips** [comment]
RC's daemon executable was not updated in v2.74.
I uploaded realese files in my github releases page.
https://github.com/mewlips/nx-remote-controller-mod/releases

There is a file for nx-ks2.
https://github.com/mewlips/nx-remote-controller-mod/releases/download/v0.9/nx-ks2_nx-rc-0.9.zip

**Comment by KinoSeed** [comment]
The files I used for the update were from the zip here: https://mewlips.github.io/nx-remote-controller-mod/
(maybe I forgot to update the deamon... I think I did)

I didn't see that you made it already packed for nx-ks :)

thanks
