### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by patxitron** [mewlips/nx-remote-controller-mod#14]
Hello. I just installed your app and works great. However, I would like to use the API used by web page to control the camera so I can automate some actions for my astrophotography shoots. Do you have some docs about the API?

Best regards.

**Comment by mewlips** [comment]
https://github.com/mewlips/nx-remote-controller-mod/wiki/API-Documentation

to take picture
<pre>
$ curl http://<camera_ip>/api/v1/input/inject?keydown=Super_L
$ curl http://<camera_ip>/api/v1/input/inject?keydown=Super_R
$ curl http://<camera_ip>/api/v1/input/inject?keyup=Super_R
$ curl http://<camera_ip>/api/v1/input/inject?keyup=Super_L
</pre>

**Comment by patxitron** [comment]
Thank you very much!
