### ISSUE TITLE
No live picture in NX300

### ISSUE THREAD

**Issue by Inveniari** [mewlips/nx-remote-controller-mod#20]
A very nice application. Unfortunately the critical part of it, the live view, is not working on NX300. Tried on Android's latest versions and also with an old Android 5.0 version. Windows 10 doesn't show the live view either.

**Comment by vachiriac** [comment]
Experiencing the same thing, have you found a way to fix this?

**Comment by Inveniari** [comment]
Unfortunately, the bug still exists. The latest update is from 2016...

**Comment by Inveniari** [comment]
I asked ChatGPT-4 to analyze the live view problem in liveview.js
Here is the answer:

From the given code, the nv12toRgba and nv12toRgba2 functions are responsible for converting the NV12 format image data from the camera to RGBA format, which is then displayed on the canvas. The issue might be in these conversions, specifically how the UV chroma samples are being applied to the Y luma samples.

The NV12 image format represents an image in YUV color space where:

Y samples are taken at every pixel
U and V samples are taken at every second pixel horizontally and vertically
In the nv12toRgba function, it seems that U and V chroma samples are applied to adjacent Y samples in a stride of 2, not only horizontally but also vertically which might not be correct. This means that the function might be using UV chroma samples for the wrong Y luma samples.

The specific code is:

javascript
Copy code
u = nv12[offset + k] & 0xff;
v = nv12[offset + k + 1] & 0xff;
u = u - 128;
v = v - 128;

// ...

if (i != 0 && (i+2) % width == 0) {
    i += width;
}
In the nv12toRgba2 function, there seems to be an analogous issue. It appears to be applying the same UV chroma samples to a block of 4 pixels. This may be incorrect if the chroma subsampling is not 4:2:0 (which would mean each UV pair is shared among a block of 4 Y samples).

The specific code is:

javascript
Copy code
y = nv12[i] & 0xff;
u = (nv12[offset + k] & 0xff) - 128;
v = (nv12[offset + k + 1] & 0xff) - 128;

// ...

if (i != 0 && (i+1) % (width / 2) == 0) {
    j += width * 4;
}
I recommend rechecking the UV chroma sample positions and their corresponding Y luma samples according to the NV12 format specification and the specific chroma subsampling used by your camera. The stripes on the screen could be due to incorrect UV-Y association, which results in color distortion.
