### ISSUE TITLE
[NX300] Everything works, except taking a picture

### ISSUE THREAD

**Issue by yringot** [mewlips/nx-remote-controller-mod#21]
Hi. Just stumbled upon this project which looks very promising. And everything works on my nx300 ....  except taking an actual picture. 😂

I can switch modes, go into settings, everything, even take a video. But if I click on the regular shutter button in the web interface, all the camera does is focus. I tried long pressing, double clicking, to no avail. Am I missing something?

NX300 firmware version: 1.40
I'm using Firefox 116.02 64 bit 

EDIT: I figured out that by using the One touch shot function I could use the mouse to click into the viewport and take a picture this way. But I'd still like to get it working properly... Any ideas?

**Comment by trilkin-github** [comment]
Hi yringot,
did you eventually find a solution? I am in the same situaton right now like you back then :).

**Comment by mruzaini** [comment]
Can try sliding down the button to take a photo

**Comment by yringot** [comment]
Thank you, that works!

Wow, what a coincidence. I just came back from vacations and wanted to 
see if there had been any progress on this issue. Thank you!
