### ISSUE TITLE
BUG: Uninstall doesn't work.

### ISSUE THREAD

**Issue by Tommixoft** [mewlips/nx-remote-controller-mod#3]
Tested uninstall function but it does nothing. Strange. :)

**Comment by Tommixoft** [comment]
PS i was using nx patch 5.1 maybe because of it.

**Comment by mewlips** [comment]
My mod installs EV_MOBILE.sh to /opt/usr/nx-on-wake. because without of it, there is no method to start my mod.
In uninstall script, only remove the /opt/usr/apps/nx-remote-controller-mod folder.

nx-patch should be provide the EV_MOBILE.sh script for launch the another apps like my mod.

**Comment by Tommixoft** [comment]
but by looking into unsinstall.sh i see you turn off swap. so it's ok to just delete folder which holds the swapfile? I just reflashed Firmware to be 100% sure im clean.
REALLY like your mod. it amazes me. how cool you did it. I dont need remote app, but it impresses me from developer's perspective. Im windows c# and php developer, only learning android..and your code so efficient, no bullshit. Really like :)
Also GREAT idea of broadcasting camera packets to lan so app would find camera ip, so no need to enter it to app.

PS what im missing is some kind of change log when committing to git.

**Comment by mewlips** [comment]
uninstall.sh fixed. see 19b16e7715b0db77512e15688ead7dddb4a99ab6.
And, no longer create a swapfile. fcf5f0c69a538af65a528875cb16563e98fcd1ac
