### ISSUE TITLE
Several viewfinders in the same html page ?

### ISSUE THREAD

**Issue by PhilZMZ** [mewlips/nx-remote-controller-mod#6]
I own 6 NX500, and I syncrhonize the shooting with a cable via micro USB, and I would be interested in monitoring these 6 cameras together.
Something that would be great : have the ability to display only the viewfinder of the 6 cameras in the browser, not the "buttons". Could you add a close box to hide them ? Or maybe display several viewfinders in the same HTML page ? Maybe I can do this with iframes...

**Comment by mewlips** [comment]
Good suggestion! :)
In the next version, I will implement this feature.

**Comment by mewlips** [comment]
Implemented in v0.9
